server:
  servlet:
    context-path: /authentication-app

spring:
  h2:
    console:
      enabled: true
      settings:
        trace: true
        web-allow-others: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false